#!/bin/bash 

dbus-monitor --system |
	while read -r line
	do
		if [[ ! -z $a ]]
		then
			volume=$(echo $line | cut -d' ' -f3)%
			pactl set-sink-volume bluez_sink.08_DF_1F_9A_66_6C.a2dp_sink $volume
			unset a
		fi
		a="`echo $line | grep Volume`"
	done
